# Generated by Django 5.2.4 on 2025-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_meeting_meetingparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='jwt_token',
            new_name='kit_token',
        ),
        migrations.AddField(
            model_name='meeting',
            name='zego_app_id',
            field=models.BigIntegerField(default=1551231778),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='domain',
            field=models.CharField(default='zegocloud', max_length=255),
        ),
    ]
