# Generated by Django 5.2.4 on 2025-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.UUIDField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
