# Generated by Django 5.2.4 on 2025-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_uuid_alter_chatroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
