# Generated by Django 5.2.1 on 2025-09-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
