# Generated by Django 5.2.1 on 2025-09-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_remove_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_cource',
            new_name='is_course',
        ),
    ]
