# Generated by Django 5.2.4 on 2025-08-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_user_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='replay',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
