# Generated by Django 5.2.4 on 2025-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_contactus_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='replay',
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
