# Generated by Django 5.2.1 on 2025-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_status_creator_approve_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=20),
        ),
    ]
