# Generated by Django 5.2.1 on 2025-08-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_creator_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='profile',
            new_name='background',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
