# Generated by Django 5.2.4 on 2025-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='publicProfile1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='publicProfile2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
