# Generated by Django 5.2.4 on 2025-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creator_publicprofile1_creator_publicprofile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
